---
# docker-compose.yaml
version: "3"
services:
  jenkins:
    image:  jenkins:2.60.3-alpine
    container_name: jenkins_service
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 8082:50000
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    restart: always

  nexus:
    image: sonatype/nexus3
    container_name: nexus_service
    ports: 
      - 8081:8081
    volumes:
      - nexus-data:/nexus-data
    networks:
      - mynetwork
    restart: always

  sonarqube:
    image: sonarqube:alpine
    container_name: sonarqube_service
    depends_on:
      - postgres
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - 9000:9000
    networks:
      - mynetwork
    restart: always

  postgres:
    image: postgres:alpine
    container_name: postgres_service
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    restart: always

  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer_service
    ports:
      - 8000:8000
      - 9443:9443
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    restart: always

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  portainer_data:
  nexus-data:
  jenkins_data:

networks:
  mynetwork:
